### ISSUE TITLE
Some minor demo glitches

### ISSUE THREAD

**Issue by willemx** [yohanboniface/Leaflet.Editable#11]
Some things I noticed when playing with the demo's:
Ctrl-clicking to make holes in polygons or to extend a polyline does not work om my Mac. It does work on my Windows machine.
When creating a new marker, a spurious marker temporarily appears on a random spot on the map. This marker then disappears when I move the cursor to place the new marker.

Thanks for this great package!
It arrives just in time for me now that I need to make a mobile app for use on tablets. I was using (the also great) leaflet-draw, but it has no touch support.

**Comment by yohanboniface** [comment]
> Ctrl-clicking to make holes in polygons or to extend a polyline does not work om my Mac. It does 
> work on my Windows machine.

Right. This is because Mac always do things on its own, and hijack the use of ctrl-click. I may switch to alt-click for the demo, good point.

> When creating a new marker, a spurious marker temporarily appears on a random spot on the
> map. This marker then disappears when I move the cursor to place the new marker.

Exact. This occurs because at the exact moment you click on the button, your mouse cursor is not over the map itself (but over the button), so the map doesn't know its position, and map center is used by default. I'll make that more friendly :)

**Comment by willemx** [comment]
About the marker position: you could just show the marker where the cursor is (over the button), as leaflet-draw is also doing...
