### ISSUE TITLE
Bug in Create hole in a polygon by ctrl-clicking on it

### ISSUE THREAD

**Issue by MelnikVasya** [yohanboniface/Leaflet.Editable#17]
[Create hole in a polygon by ctrl-clicking on it](http://yohanboniface.github.io/Leaflet.Editable/example/create-hole-on-click.html) 
When I create a second hole point in the polygon I get error
```console
Failed to load resource: net::ERR_FILE_NOT_FOUND --> Leaflet.Editable.js:795 
Uncaught TypeError: Cannot read property 'unshift' of undefined --> Leaflet.Editable.js:795 
L.Editable.PathEditor.L.Editable.BaseEditor.extend.addLatLng --> Leaflet.Editable.js:802 
L.Editable.PathEditor.L.Editable.BaseEditor.extend.newPointForward --> Leaflet.Editable.js:974 
L.Editable.PolygonEditor.L.Editable.PathEditor.extend.newHolecreate-hole-on-click.html:39 (anonymous function) --> leaflet.js:5 
o.Evented.o.Class.extend.fire --> leaflet.js:5 
o.Map.o.Evented.extend._fireDOMEvent --> leaflet.js:5 
o.Map.o.Evented.extend._handleDOMEven --> tleaflet.js:8
 h
```
![screenshot from 2015-04-02 20_12_26](https://cloud.githubusercontent.com/assets/5058192/6969557/4496f97a-d978-11e4-8318-bb5cdebadc5e.png)

**Comment by yohanboniface** [comment]
Sorry, totally missed you issue (Github notification are a mess :/).

This is due to a conflict with Leaflet master, see https://github.com/Leaflet/Leaflet/pull/3307

If you need to use Leaflet.Editable in production, I suggest that you use the leaflet0.7 branch with Leaflet 0.7.3. If you need to use Leaflet master, you can integrate my PR, but I don't think it will be the final one so I discourage you to do so ;)

**Comment by yohanboniface** [comment]
Should be fixed in latest trunks.
